### ISSUE TITLE
1. Join/Unjoin waiting list. {US 01.01.01, US 01.01.02} - Alina

### ISSUE THREAD

**Issue by Lopez179** [CMPUT301F24prince/princeProject#1]
- Entrants should be able to join and unjoin waiting lists
- Entrants should be notified when chosen from the waiting list

Medium risk

**Comment by mikhailjivraj** [comment]
Stories grouped together as it relates to joining and leaving the waiting list to an event (user interactions for an event)
Story points: 3/5
