### ISSUE TITLE
17. Organizer views event interactions {US 02.06.03, US 02.06.04} - Kyle

### ISSUE THREAD

**Issue by Lopez179** [CMPUT301F24prince/princeProject#17]
Organizers should be able to view the following for their event:
- List of all chosen applicants invited to apply
- List of all entrants who canceled
- List of all entrants who are enrolled in the event

Medium risk

**Comment by mikhailjivraj** [comment]
Stories grouped together - Functionality for organizers to manage users that interact with their event
Story points: 3/5
