### ISSUE TITLE
19. Organizer send notifications {US 02.07.01, US 02.07.02, US 02.07.03}

### ISSUE THREAD

**Issue by Lopez179** [CMPUT301F24prince/princeProject#19]
Organizers can send notifications to the following sets of entrants
- all entrants on the waiting list
- all selected entrants
- all canceled entrants

Low risk

**Comment by mikhailjivraj** [comment]
Stories are grouped together as they relate to notification handling for organizers to send notifications to users.
Story Points: 3/5
