### ISSUE TITLE
2. Implement profile {US 01.02.01, US 01.02.02} - Mikhail

### ISSUE THREAD

**Issue by Lopez179** [CMPUT301F24prince/princeProject#2]
- Server should track the following information: (name, email, phone number)
- phone number is optional
- The user should be able to update this info

Though this was only mentioned for entrant users, it's safe to assume this extends to organizers, admins, and all users in general.

Low risk

**Comment by mikhailjivraj** [comment]
Stories grouped together as they relate to creating/editing a profile
Story points: 2/5
