### ISSUE TITLE
6. Entrant chosen in waiting list {US 01.05.02, US 01.05.03, US 01.05.01} - Awais

### ISSUE THREAD

**Issue by Lopez179** [CMPUT301F24prince/princeProject#6]
- A user in a waiting list can be chosen, in which they are given an invitation
- Users should be able to accept/decline when chosen for an even in a waiting list
- Should a user decline an invitation, a new entrant can be chosen

High risk

**Comment by mikhailjivraj** [comment]
Stories grouped together as they relate to user interaction with an event once the lottery is complete (handling invitations or joining wait lists)
Story points: 4/5
